const path = require('path');
process.chdir(__dirname);
const { GatewayIntentBits, Client, Collection } = require('discord.js');
const { install: installProfessionalSuite } = require('./ProfessionalSuite');
const { install: installGovernance } = require('./GovernanceSuite');
const { install: installProduction } = require('./ProductionSuite');
const { install: installSecurity } = require('./SecuritySuite');
const { install: installLogs } = require('./LogSuite');
const { install: installLegacyTicketStaff } = require('./LegacyTicketStaff');
const { ensure: ensurePayments } = require('./PaymentProviders');
const { installProcessHandlers, recordError } = require('./Lib/Resilience');
const { installInteractionGuard, wrapInteractionHandler } = require('./InteractionGuard');
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessageReactions, GatewayIntentBits.DirectMessages] });
const originalClientOn = client.on.bind(client);
client.on = (event, listener) => originalClientOn(event, event === 'interactionCreate' && !listener.__interactionGuard ? wrapInteractionHandler(listener) : listener);
const EstatisticasNode = new (require('./Functions/VariaveisEstatisticas'))();
module.exports = { EstatisticasNode };
async function start() {
  const { initialize } = require('./DatabasePostgres'); await initialize();
  const events = require('./Handler/events'); const slash = require('./Handler/slash');
  client.slashCommands = new Collection(); slash.run(client); events.run(client);
  installInteractionGuard(client); installProcessHandlers(client); installProfessionalSuite(client); installGovernance(client); installProduction(client); installSecurity(client); installLogs(client); installLegacyTicketStaff(client); ensurePayments();
  const token = typeof process.env.DISCORD_TOKEN === 'string' ? process.env.DISCORD_TOKEN.trim() : '';
  if (!token) throw new Error('Defina DISCORD_TOKEN no Render antes de iniciar o bot.');
  console.log('[Discord] Iniciando Gateway com token configurado');
  const signals = [['hello',/\bhello\b/i],['identify',/\bidentify\b/i],['heartbeat',/\bheartbeat\b/i],['ready',/\bready\b/i],['resumed',/\bresumed\b/i],['close',/close|disconnect/i],['error',/error|invalid session|rate.?limit/i]];
  client.on('debug', message => { const s=signals.find(([,p])=>p.test(message)); if(s) console.log('[Discord Gateway debug] '+s[0]); });
  client.on('shardCreate', shard => console.log('[Discord] Shard criado: '+shard.id));
  client.on('shardReady', id => console.log('[Discord] Gateway pronto; shard '+id));
  client.once('ready', () => console.log('[Discord] Bot autenticado como '+client.user.tag+' ('+client.user.id+')'));
  client.on('shardReconnecting', id => console.warn('[Discord] Reconectando shard '+id));
  client.on('shardDisconnect', (event,id) => console.error('[Discord] Gateway desconectou', {shardId:id,code:event?.code??null,reason:event?.reason?.toString?.()||''}));
  client.on('shardError', (error,id) => recordError(error,{type:'discordShardError',shardId:id}));
  setTimeout(() => { if(!client.isReady()) console.error('[Discord] Gateway ainda sem READY após 60s',{wsStatus:client.ws?.status??null}); },60000).unref();
  await client.login(token);
}
start().catch(error => { recordError(error,{type:'startup'}); console.error('[Startup] '+error.message); process.exitCode=1; });
