const path = require('path');
process.chdir(__dirname);
const { GatewayIntentBits, Client, Collection } = require('discord.js');
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessageReactions, GatewayIntentBits.DirectMessages] });
client.setMaxListeners(0);
const { install: installProfessionalSuite } = require('./ProfessionalSuite');
const { install: installGovernance } = require('./GovernanceSuite');
const { install: installProduction } = require('./ProductionSuite');
const { install: installSecurity } = require('./SecuritySuite');
const { install: installLogs } = require('./LogSuite');
const { install: installLegacyTicketStaff } = require('./LegacyTicketStaff');
const { ensure: ensurePayments } = require('./PaymentProviders');
const { installProcessHandlers, recordError } = require('./Lib/Resilience');
const { installInteractionGuard, wrapInteractionHandler } = require('./InteractionGuard');
const EstatisticasNode = new (require('./Functions/VariaveisEstatisticas'))();
module.exports = { EstatisticasNode };
async function start() {
  await require('./DatabasePostgres').initialize();
  const events = require('./Handler/events');
  const slash = require('./Handler/slash');
  client.slashCommands = new Collection();
  slash.run(client); events.run(client);
  installInteractionGuard(client); installProcessHandlers(client);
  installProfessionalSuite(client); installGovernance(client); installProduction(client);
  installSecurity(client); installLogs(client); installLegacyTicketStaff(client); ensurePayments();
  const token = String(process.env.DISCORD_TOKEN || '').trim();
  if (!token) throw new Error('Defina DISCORD_TOKEN no Render.');
  client.once('ready', () => console.log('[Discord] Bot autenticado como', client.user.tag, client.user.id));
  client.on('error', error => recordError(error, { type: 'discordClientError' }));
  await client.login(token);
}
start().catch(error => { recordError(error, { type: 'startup' }); console.error('[Startup]', error); process.exitCode = 1; });
