const path = require('path');
process.chdir(__dirname);
const { GatewayIntentBits, Client, Collection } = require('discord.js');
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessageReactions, GatewayIntentBits.DirectMessages] });
client.setMaxListeners(0);
const { install: installProfessionalSuite } = require('./ProfessionalSuite');
const { install: installGovernance } = require('./GovernanceSuite');
const { install: installProduction } = require('./ProductionSuite');
const { install: installSecurity } = require('./SecuritySuite');
const { install: installLogs } = require('./LogSuite');
const { install: installLegacyTicketStaff } = require('./LegacyTicketStaff');
const { ensure: ensurePayments } = require('./PaymentProviders');
const { installProcessHandlers, recordError } = require('./Lib/Resilience');
const { installInteractionGuard } = require('./InteractionGuard');
const EstatisticasNode = new (require('./Functions/VariaveisEstatisticas'))();
module.exports = { EstatisticasNode };
const token = String(process.env.DISCORD_TOKEN || '').trim();
if (!token) throw new Error('Defina DISCORD_TOKEN no Render.');
client.once('ready', () => console.log('[Discord] READY autenticado como ' + client.user.tag + ' (' + client.user.id + ')'));
client.on('error', error => console.error('[Discord] ERROR ' + error.message));
client.on('shardError', error => console.error('[Discord] SHARD_ERROR ' + error.message));
async function start() {
  console.log('[Startup] iniciando bot');
  installProfessionalSuite(client);
  console.log('[Startup] dashboard iniciado; iniciando login Discord');
  client.login(token).then(() => console.log('[Discord] login concluido')).catch(error => { console.error('[Discord] LOGIN_ERROR ' + error.message); process.exitCode = 1; });
  await require('./DatabasePostgres').initialize();
  const events = require('./Handler/events');
  const slash = require('./Handler/slash');
  client.slashCommands = new Collection();
  slash.run(client); events.run(client);
  installInteractionGuard(client); installProcessHandlers(client);
  installGovernance(client); installProduction(client); installSecurity(client);
  installLogs(client); installLegacyTicketStaff(client); ensurePayments();
  console.log('[Startup] extensoes carregadas');
}
start().catch(error => { console.error('[Startup] FALHA ' + error.message); try { recordError(error, { type: 'startup' }); } catch (_) {} process.exitCode = 1; });
