const fs = require('fs');
const path = require('path');
const express = require('express');
const { withTimeout, snapshot, backupJson, recordError, once, release, runLimited } = require('./Lib/Resilience');
const { mirrorDocument, storageStatus } = require('./DatabasePostgres');
const {
  Events, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle,
  ModalBuilder, TextInputBuilder, TextInputStyle, PermissionFlagsBits
} = require('discord.js');


const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, 'DataBaseJson');
const DATA_FILE = path.join(DATA_DIR, 'professional.json');
const DEFAULTS = {
  settings: { logChannelId: '', starboardChannelId: '', suggestionChannelId: '', welcomeChannelId: '', goodbyeChannelId: '', ticketCategoryId: '', ticketTeamRoleId: '', inactivityHours: 72, slaHours: 24, dashboardPort: 8787 },
  reactionRoles: {}, customCommands: {}, teams: {}, forms: {}, permissions: {},
  starboard: {}, suggestions: {}, tickets: {}, transcripts: {}, supportMetrics: { firstResponseMs: [], resolutionMs: [], byTeam: {}, byAgent: {} }, stats: { opened: 0, closed: 0, byTeam: {}, byAgent: {}, totalMessages: 0 },
  automod: { enabled: true, blockedWords: [], maxMentions: 5, maxLinksPerMessage: 3, spamWindowSeconds: 10, spamMaxMessages: 6, inviteLinks: true, exemptions: { channels: [], roles: [] }, punish: 'timeout' }, audit: { events: [], max: 1000 }
};
function clone(v) { return JSON.parse(JSON.stringify(v)); }
function load() { try { return { ...clone(DEFAULTS), ...JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')) }; } catch { fs.mkdirSync(DATA_DIR, { recursive: true }); save(clone(DEFAULTS)); return clone(DEFAULTS); } }
let db;
function save(next = db) { db = next; fs.mkdirSync(DATA_DIR, { recursive: true }); fs.writeFileSync(DATA_FILE, JSON.stringify(db, null, 2)); mirrorDocument('professional', db); }
let saveTimer = null;
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(() => { try { save(); } catch (error) { console.error('[ProfessionalSuite] Falha ao persistir alterações:', error); } }, 250); }
db = load();
function allowed(member, key) { const ids = db.permissions[key] || []; return !ids.length || member.permissions.has(PermissionFlagsBits.Administrator) || ids.some(id => member.roles.cache.has(id)); }
async function log(client, guild, title, description, color = 0x5865f2) { const id = db.settings.logChannelId; if (!id) return; const ch = await guild.channels.fetch(id).catch(() => null); if (ch?.isTextBased()) await ch.send({ embeds: [new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).setTimestamp()] }).catch(() => {}); }
function transcript(channel, messages) { return `<!doctype html><html lang="pt-br"><meta charset="utf-8"><title>Transcript ${channel.name}</title><style>body{font:15px system-ui;background:#0f1117;color:#e6e9ef;max-width:1000px;margin:40px auto;padding:0 20px}article{padding:12px;border-bottom:1px solid #2b3040}small{color:#9aa4b2}a{color:#78a9ff}</style><h1>${channel.name}</h1>${messages.map(m => `<article><b>${m.author?.tag || 'usuário'}</b> <small>${new Date(m.createdTimestamp).toISOString()}</small><div>${String(m.cleanContent || '').replace(/[&<>]/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}</div>${[...(m.attachments?.values?.() || [])].map(a => `<a href="${a.url}" target="_blank">Anexo: ${a.name || a.url}</a>`).join('<br>')}</article>`).join('')}</html>`; }
async function closeTicket(channel, reason = 'inatividade') { return runLimited(() => closeTicketImpl(channel, reason), 'professional-ticket-close', 2); }
async function closeTicketImpl(channel, reason = 'inatividade') { if (!channel?.isThread?.() && !channel?.isTextBased?.()) return; const ticket = db.tickets[channel.id]; const list = []; let before; for (let page = 0; page < 20; page++) { const batch = await channel.messages.fetch({ limit: 100, ...(before ? { before } : {}) }).catch(() => null); if (!batch?.size) break; list.push(...batch.values()); before = batch.last().id; if (batch.size < 100) break; } list.reverse(); const id = `${channel.guildId}-${channel.id}-${Date.now()}`; db.transcripts[id] = { id, guildId: channel.guildId, channelId: channel.id, name: channel.name, reason, createdAt: new Date().toISOString(), messageCount: list.length, html: transcript(channel, list) }; db.stats.closed++; db.supportMetrics ||= { firstResponseMs: [], resolutionMs: [], byTeam: {}, byAgent: {} }; if (ticket) { db.supportMetrics.resolutionMs.push(Date.now() - Number(ticket.openedAt || Date.now())); if (ticket.agentId) { db.supportMetrics.byAgent[ticket.agentId] ||= { messages: 0, closed: 0 }; db.supportMetrics.byAgent[ticket.agentId].closed++; } if (ticket.team) db.supportMetrics.byTeam[ticket.team] = (db.supportMetrics.byTeam[ticket.team] || 0) + 1; delete db.tickets[channel.id]; } save(); await log(channel.client, channel.guild, 'Ticket fechado', `**${channel.name}**\nMotivo: ${reason}`, 0xed4245); if (channel.isThread?.()) await channel.setArchived(true, reason).catch(() => {}); else await channel.delete(reason).catch(() => {}); }
function startDashboard(client) { const app = express(); app.use(express.json()); const dashboardToken = process.env.DASHBOARD_TOKEN; const publicDashboard = process.env.DASHBOARD_PUBLIC === 'true'; if (publicDashboard && !dashboardToken) throw new Error('DASHBOARD_TOKEN é obrigatório quando DASHBOARD_PUBLIC=true'); const payments = require('./PaymentProviders'); payments.ensure(); app.use(['/api', '/transcripts'], (req, res, next) => { if (!dashboardToken) return next(); const auth = req.headers.authorization || ''; if (auth === `Bearer ${dashboardToken}`) return next(); return res.status(401).json({ error: 'Não autorizado' }); }); app.get('/health', (_, res) => res.json({ ok: true, service: 'Shadow Games Professional Suite', discordReady: Boolean(client.ws?.status === 0), uptimeSeconds: Math.floor(process.uptime()) }));
  app.get('/ready', (_, res) => { const ready = Boolean(client.isReady?.()); return res.status(ready ? 200 : 503).json({ ok: ready, discordReady: ready, uptimeSeconds: Math.floor(process.uptime()) }); });
  app.get('/api/health/details', (req, res) => res.json({ ...snapshot(), db: { ...storageStatus(), tickets: Object.keys(db.tickets || {}).length, transcripts: Object.keys(db.transcripts || {}).length } })); app.get('/api/stats', (req, res) => res.json({ ...db.stats, support: db.supportMetrics || {}, activeTickets: Object.values(db.tickets).map(({ answers, ...t }) => t) })); app.get('/api/teams', (req, res) => res.json(db.teams || {})); app.get('/api/forms', (req, res) => res.json(db.forms || {})); app.get('/api/tickets', (req, res) => res.json(db.tickets || {})); app.get('/api/transcripts', (req, res) => res.json(Object.values(db.transcripts).map(({ html, ...x }) => x))); app.get('/api/audit', (req, res) => res.json(db.audit || { events: [] })); app.get('/api/config', (req, res) => res.json({ settings: db.settings, automod: db.automod, permissions: db.permissions })); app.get('/api/payments/providers', (req, res) => res.json(Object.fromEntries(Object.entries(payments.PROVIDERS).map(([key, value]) => [key, { name: value.name, configured: payments.configured(key), docs: value.docs }])))); app.get('/api/payments/status', (req, res) => res.json(payments.status())); app.post('/api/payments/select', (req, res) => { try { return res.json(payments.select(req.body.provider, req.body.mode || 'sandbox')); } catch (e) { return res.status(400).json({ error: e.message }); } }); app.post('/webhooks/payments/:provider', (req, res) => { const result = payments.processWebhook(req.params.provider, req.body, (req.headers['asaas-access-token'] || req.headers['x-signature'])); if (result.ok && result.paid && result.ref) { require('./Functions/VerficarPagamento').VerificarPagamento(client).catch(error => console.error('[Asaas webhook] Falha ao iniciar aprovação:', error)); } return res.status(result.ok ? 200 : 400).json(result); }); app.get('/transcripts/:id', (req, res) => db.transcripts[req.params.id] ? res.type('html').send(db.transcripts[req.params.id].html) : res.status(404).send('Transcript não encontrado')); app.get('/', (_, res) => res.send(`<h1>Shadow Games — Dashboard</h1><p>Tickets abertos: ${db.stats.opened} · fechados: ${db.stats.closed}</p><p>Equipes: ${Object.keys(db.teams || {}).length} · Tickets ativos: ${Object.keys(db.tickets || {}).length}</p><p><a href="/api/stats">Estatísticas</a> · <a href="/api/payments/status">Pagamento selecionado</a> · <a href="/api/payments/providers">Provedores</a></p>`)); const port = Number(process.env.PORT || process.env.DASHBOARD_PORT || db.settings.dashboardPort || 8787); const host = process.env.PORT || publicDashboard ? '0.0.0.0' : '127.0.0.1'; const server = app.listen(port, host, () => console.log(`[ProfessionalSuite] Dashboard em http://${host}:${port}`)); return server; }
async function handleMessage(message, client) {
  if (!message.guild || message.author.bot) return;
  db.stats.totalMessages++; scheduleSave();
  const content = message.content.toLowerCase();
  const cmd = message.content.match(/^\!([\w-]+)(?:\s+([\s\S]+))?$/); if (cmd && db.customCommands[cmd[1]]) await message.channel.send(String(db.customCommands[cmd[1]]).replaceAll('{user}', `${message.author}`));
  if (content.startsWith('!sugestao ')) { const text = message.content.slice(10).trim(); const ch = db.settings.suggestionChannelId ? await message.guild.channels.fetch(db.settings.suggestionChannelId).catch(() => null) : message.channel; if (ch?.isTextBased()) await ch.send({ embeds: [new EmbedBuilder().setColor(0xfee75c).setTitle('💡 Nova sugestão').setDescription(text).setFooter({ text: `Por ${message.author.tag}` })], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('suggestion_up').setLabel('Aprovar').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId('suggestion_down').setLabel('Reprovar').setStyle(ButtonStyle.Danger))] }); await message.delete().catch(() => {}); }
}
async function handleInteraction(interaction, client) {
  if (interaction.isButton() && interaction.customId === 'ticket_open') { const modal = new ModalBuilder().setCustomId('ticket_form').setTitle('Abrir atendimento').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('subject').setLabel('Assunto').setStyle(TextInputStyle.Short).setRequired(true)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('details').setLabel('Explique sua necessidade').setStyle(TextInputStyle.Paragraph).setRequired(true))); return interaction.showModal(modal); }
  if (interaction.isModalSubmit() && interaction.customId === 'ticket_form') { const actionKey = `ticket-create:${interaction.guildId}:${interaction.user.id}`; if (!once(actionKey, 30000)) return interaction.reply({ content: '⏳ Seu ticket já está sendo criado. Aguarde um instante.', ephemeral: true }); const subject = interaction.fields.getTextInputValue('subject'); const details = interaction.fields.getTextInputValue('details'); await interaction.deferReply({ ephemeral: true }); const guild = interaction.guild; const channel = await withTimeout(guild.channels.create({ name: `ticket-${interaction.user.username}`.slice(0, 90), parent: db.settings.ticketCategoryId || undefined, topic: JSON.stringify({ ownerId: interaction.user.id, team: 'geral', lastActivity: Date.now() }), permissionOverwrites: [{ id: guild.roles.everyone.id, deny: [PermissionFlagsBits.ViewChannel] }, { id: interaction.user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages] }, ...(db.settings.ticketTeamRoleId ? [{ id: db.settings.ticketTeamRoleId, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages] }] : [])] }), 20000, 'criação do ticket'); db.tickets[channel.id] = { channelId: channel.id, ownerId: interaction.user.id, subject, team: 'geral', openedAt: Date.now(), lastActivity: Date.now() }; db.stats.opened++; save(); await withTimeout(channel.send({ content: `<@${interaction.user.id}>${db.settings.ticketTeamRoleId ? ` <@&${db.settings.ticketTeamRoleId}>` : ''}`, embeds: [new EmbedBuilder().setColor(0x57f287).setTitle(subject).setDescription(details)], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_close').setLabel('Fechar ticket').setStyle(ButtonStyle.Danger), new ButtonBuilder().setCustomId('ticket_claim').setLabel('Assumir').setStyle(ButtonStyle.Primary))] }), 15000, 'mensagem inicial do ticket'); release(actionKey); return interaction.editReply({ content: `✅ Atendimento criado: ${channel}` }); }
  if (interaction.isButton() && interaction.customId === 'ticket_close') { if (!allowed(interaction.member, 'closeTicket')) return interaction.reply({ content: 'Sem permissão.', ephemeral: true }); await interaction.reply({ content: 'Fechando e salvando o transcript...', ephemeral: true }); return closeTicket(interaction.channel, `fechado por ${interaction.user.tag}`); }
  if (interaction.isButton() && interaction.customId === 'ticket_claim') { if (!allowed(interaction.member, 'claimTicket')) return interaction.reply({ content: 'Sem permissão.', ephemeral: true }); const t = db.tickets[interaction.channel.id]; if (t) { t.agentId = interaction.user.id; t.lastActivity = Date.now(); save(); } return interaction.reply({ content: `✅ Ticket encaminhado para ${interaction.user}.`, ephemeral: false }); }
  if (interaction.isButton() && /^suggestion_/.test(interaction.customId)) { if (!allowed(interaction.member, 'moderateSuggestions')) return interaction.reply({ content: 'Sem permissão.', ephemeral: true }); const old = interaction.message.embeds[0]; const vote = interaction.customId === 'suggestion_up' ? 'Aprovada' : 'Reprovada'; return interaction.update({ embeds: [EmbedBuilder.from(old).setTitle(`${vote}: ${old.title}`)], components: [] }); }
}
function install(client) {
  client.on(Events.MessageCreate, m => handleMessage(m, client));
  client.on(Events.MessageDelete, m => { if (m.guild && !m.author?.bot) log(client, m.guild, 'Mensagem apagada', `Canal: ${m.channel}\nAutor: ${m.author || 'desconhecido'}\nConteúdo: ${m.content || '*indisponível*'}`, 0xed4245); });
  client.on(Events.MessageUpdate, (before, after) => { if (after.guild && !after.author?.bot && before.content !== after.content) log(client, after.guild, 'Mensagem editada', `Canal: ${after.channel}\nAutor: ${after.author}\nAntes: ${before.content || '*vazio*'}\nDepois: ${after.content || '*vazio*'}`, 0xfee75c); });
  client.on(Events.InteractionCreate, i => handleInteraction(i, client).catch(e => { recordError(e, { type: 'interaction', customId: i.customId, command: i.commandName }); if (!i.replied && !i.deferred) i.reply({ content: '❌ Ocorreu um erro temporário. Tente novamente.', ephemeral: true }).catch(() => {}); }));
  client.on(Events.MessageReactionAdd, async (reaction, user) => {
    const cfg = db.reactionRoles[reaction.message.id]?.[reaction.emoji.id || reaction.emoji.name];
    const member = await reaction.message.guild?.members.fetch(user.id).catch(() => null);
    if (cfg && member) await member.roles.add(cfg).catch(() => {});
  });
  client.on(Events.MessageReactionRemove, async (reaction, user) => {
    const cfg = db.reactionRoles[reaction.message.id]?.[reaction.emoji.id || reaction.emoji.name];
    const member = await reaction.message.guild?.members.fetch(user.id).catch(() => null);
    if (cfg && member) await member.roles.remove(cfg).catch(() => {});
  });
  client.on(Events.GuildMemberAdd, member => { const id = db.settings.welcomeChannelId; if (id) member.guild.channels.fetch(id).then(ch => ch?.isTextBased() && ch.send(`👋 Bem-vindo(a), ${member}, à **${member.guild.name}**!`)).catch(() => {}); });
  client.on(Events.GuildMemberRemove, member => { const id = db.settings.goodbyeChannelId; if (id) member.guild.channels.fetch(id).then(ch => ch?.isTextBased() && ch.send(`Até mais, **${member.user.tag}**.`)).catch(() => {}); });
  setInterval(async () => { const limit = Number(db.settings.inactivityHours || 72) * 3600000; for (const id of Object.keys(db.tickets)) { const t = db.tickets[id]; if (Date.now() - Number(t.lastActivity || t.openedAt) > limit) { const ch = await client.channels.fetch(id).catch(() => null); if (ch) await closeTicket(ch, 'inatividade automática'); delete db.tickets[id]; save(); } } }, 15 * 60 * 1000);
  const backupTimer = setInterval(() => { try { const file = backupJson(DATA_FILE, path.join(DATA_DIR, 'backups')); if (file) console.log(`[ProfessionalSuite] Backup criado: ${path.basename(file)}`); } catch (error) { recordError(error, { type: 'backup' }); } }, 6 * 60 * 60 * 1000); backupTimer.unref?.();
  try { backupJson(DATA_FILE, path.join(DATA_DIR, 'backups')); } catch (error) { recordError(error, { type: 'initialBackup' }); }
  startDashboard(client);
}
module.exports = { install, db, save, closeTicket, startDashboard };
