const { Events, ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const { db, save } = require('./ProfessionalSuite');
const TEAMS = { suporte: ['Suporte', 'Ajuda geral e dúvidas', '🛠️'], financeiro: ['Financeiro', 'Pagamentos e comprovantes', '💳'], vendas: ['Vendas', 'Produtos e pedidos', '🛒'], parceria: ['Parceria', 'Propostas e parcerias', '🤝'] };
function ensure(){ db.ticketPanel ||= {}; save(); return db.ticketPanel; }
function cfg(guildId){ const all=ensure(); all[guildId] ||= { title:'Central de atendimento', description:'Escolha abaixo o tipo de atendimento que precisa.', color:'#7c3aed', categoryId:'', panelChannelId:'' }; return all[guildId]; }
function panelComponents(){ return [new ActionRowBuilder().addComponents(Object.entries(TEAMS).map(([key,v])=>new ButtonBuilder().setCustomId(`tp_open:${key}`).setLabel(v[0]).setEmoji(v[2]).setStyle(ButtonStyle.Primary)))]; }
async function sendPanel(guild, channel, options={}){ const c=cfg(guild.id); Object.assign(c, options, {panelChannelId:channel.id}); save(); return channel.send({embeds:[new EmbedBuilder().setColor(c.color).setTitle(c.title).setDescription(c.description)],components:panelComponents()}); }
async function openTicket(interaction, team){ const c=cfg(interaction.guild.id), data=TEAMS[team]||TEAMS.suporte; const category=c.categoryId && interaction.guild.channels.cache.get(c.categoryId); const name=`${team}-${interaction.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,90); const overwrites=[{id:interaction.guild.roles.everyone.id,deny:['ViewChannel']},{id:interaction.user.id,allow:['ViewChannel','SendMessages','ReadMessageHistory','AttachFiles']},{id:interaction.client.user.id,allow:['ViewChannel','SendMessages','ReadMessageHistory','ManageChannels']}]; const channel=await interaction.guild.channels.create({name,type:ChannelType.GuildText,parent:category?.type===ChannelType.GuildCategory?category.id:undefined,topic:`ticket:${interaction.user.id}:${team}:aberto`,permissionOverwrites:overwrites}); await channel.send({content:`${interaction.user} | ${data[0]}`,embeds:[new EmbedBuilder().setColor('#22c55e').setTitle(data[0]).setDescription(`${data[1]}\n\nExplique sua solicitação para a equipe.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tp_claim').setLabel('Assumir').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('tp_close').setLabel('Fechar ticket').setStyle(ButtonStyle.Danger))]}); return interaction.reply({content:`✅ Ticket criado: ${channel}`,ephemeral:true}); }
async function install(client){ client.on(Events.InteractionCreate, async i=>{ try{ if(!i.guild||!i.isButton?.()) return; if(i.customId.startsWith('tp_open:')) return openTicket(i,i.customId.split(':')[1]); if(i.customId==='tp_claim'){ await i.reply({content:`✅ ${i.user} assumiu este ticket.`,ephemeral:false}); return; } if(i.customId==='tp_close'){ if(!i.memberPermissions?.has(PermissionFlagsBits.ManageChannels)) return i.reply({content:'❌ Você precisa de Gerenciar Canais.',ephemeral:true}); await i.reply({content:'🔒 Ticket fechado. Este canal será apagado em 5 segundos.'}); setTimeout(()=>i.channel.delete().catch(()=>{}),5000); } }catch(e){ if(!i.replied&&!i.deferred) i.reply({content:'❌ Não foi possível concluir esta ação.',ephemeral:true}).catch(()=>{}); } }); }
module.exports={install,sendPanel,cfg,TEAMS};
