const {Events,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits,ChannelType,AttachmentBuilder}=require('discord.js');
const {db,save}=require('./ProfessionalSuite');
const teams={suporte:{name:'Suporte ao Cliente',description:'Obter auxílio em compras de produtos',emoji:'🎧'},duvidas:{name:'Dúvidas',description:'Tire dúvidas sobre nossos produtos e dúvidas',emoji:'❓'}};
function ensure(){db.ticketConfig||={};Object.assign(db.ticketConfig,{panelTitle:'Central de Atendimento | Wolf Store',panelDescription:'Ao abrir um ticket, um integrante da equipe irá lhe responder. Nosso atendimento é privado, rápido e eficiente, disponível 24 horas por dia, sujeito à disponibilidade em horários de pico.',panelColor:'#f1c40f',panelImage:'',logsChannelId:'',...db.ticketConfig});db.ticketConfig.teams={...teams,...(db.ticketConfig.teams||{})};save()}
const slug=s=>String(s||'usuario').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').slice(0,22).replace(/^-|-$/g,'')||'usuario';
const staff=(i,t)=>i.memberPermissions?.has(PermissionFlagsBits.Administrator)||Boolean(i.member?.roles?.cache&&[t?.roleId,db.ticketConfig.permissions?.claimRole,db.ticketConfig.permissions?.closeRole].filter(Boolean).some(x=>i.member.roles.cache.has(x)));
function categoryMenu(){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('Clique aqui para ver as opções').addOptions(Object.entries(db.ticketConfig.teams).slice(0,25).map(([value,t])=>({label:t.name,description:t.description,value,emoji:t.emoji||'🎫'}))))}
function panel(){const c=db.ticketConfig,e=new EmbedBuilder().setColor('#f1c40f').setTitle('Central de Atendimento | Wolf Store').setDescription(c.panelDescription);if(c.panelImage)e.setImage(c.panelImage);return{embeds:[e],components:[categoryMenu()]}}
function actionButtons(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_notify').setLabel('Notificar').setEmoji('🔔').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket_claim').setLabel('Assumir Ticket').setEmoji('🔒').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket_close').setLabel('Deletar e Salvar').setEmoji('🗑️💾').setStyle(ButtonStyle.Danger))}
function optionMenu(){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_options').setPlaceholder('Selecione um painel de opções').addOptions({label:'Painel Staff',description:'Ferramentas exclusivas para a equipe',value:'staff',emoji:'🛠️'},{label:'Opções Clientes',description:'Opções disponíveis para você',value:'client',emoji:'👤'}))}
function purchases(i){const all=db.purchases||db.purchaseHistory||db.orders||{};const list=Array.isArray(all)?all.filter(x=>String(x.userId||x.user||x.discordId)===String(i.user.id)):all[i.user.id]||[];return Array.isArray(list)?list.slice(-25):[]}
function purchasePanel(i){const list=purchases(i),options=list.map((p,n)=>({label:`ID: ${p.id||p.orderId||n+1} - ${String(p.product||p.name||p.item||'Produto').slice(0,80)}`,value:String(p.id||p.orderId||n+1)}));return{embeds:[new EmbedBuilder().setColor('#f1c40f').setTitle('Compras encontradas').setDescription('Caso o ticket seja referente a um pedido já efetuado, clique no menu abaixo e selecione o produto.')],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_purchase').setPlaceholder('Selecione uma das últimas compras').addOptions(options.length?options:[{label:'Nenhuma compra encontrada',value:'none',emoji:'📦'}]))]}}
async function create(i,key){const t=db.ticketConfig.teams[key]||teams.suporte,g=i.guild,old=g.channels.cache.find(c=>c.topic===`ticket:${i.user.id}:${key}`);if(old)return i.reply({content:`Você já possui um ticket aberto: ${old}`,ephemeral:true});const p=[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.AttachFiles]},{id:g.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ManageChannels,PermissionFlagsBits.ReadMessageHistory]}];if(t.roleId)p.push({id:t.roleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const ch=await g.channels.create({name:`${slug(t.name)}-${slug(i.user.username)}-${String(i.user.id).slice(-4)}`,type:ChannelType.GuildText,parent:t.categoryId||undefined,topic:`ticket:${i.user.id}:${key}`,permissionOverwrites:p});const e=new EmbedBuilder().setColor('#f1c40f').setTitle(t.name).setDescription(`Olá ${i.user}, seu ticket foi criado!\\n\\nNossa equipe irá atendê-lo em breve.\\n\\n**Categoria:** ${t.name}`);await ch.send({content:`${i.user}`,embeds:[e],components:[actionButtons(),optionMenu()]});if(key==='suporte')await ch.send(purchasePanel(i));return i.reply({content:`✅ Seu ticket foi criado: ${ch}`,ephemeral:true})}
async function close(i){const key=String(i.channel.topic||'').split(':')[2];if(!staff(i,db.ticketConfig.teams[key]))return i.reply({content:'❌ Somente a equipe pode fechar este ticket.',ephemeral:true});await i.deferReply({ephemeral:true});const ms=await i.channel.messages.fetch({limit:100}),txt=[...ms.values()].map(m=>`${m.author.tag}: ${m.content||'[embed/anexo]'}`).join('\\n'),log=db.ticketConfig.logsChannelId?await i.guild.channels.fetch(db.ticketConfig.logsChannelId).catch(()=>null):null;if(log?.isTextBased())await log.send({content:`📁 Ticket fechado: **${i.channel.name}** por ${i.user}`,files:[new AttachmentBuilder(Buffer.from(txt||'Sem mensagens.'),{name:`${i.channel.name}.txt`})]});await i.editReply({content:'✅ Transcrição salva. O ticket será deletado.'});setTimeout(()=>i.channel.delete('Ticket encerrado'),1200)}
async function install(client){ensure();client.on(Events.InteractionCreate,async i=>{try{if(i.isStringSelectMenu()&&i.customId==='ticket_category')return create(i,i.values[0]);if(i.isStringSelectMenu()&&i.customId==='ticket_purchase')return i.values[0]==='none'?i.reply({content:'Não encontramos compras vinculadas a você.',ephemeral:true}):i.reply({content:'Certo, informei sobre seu pedido para a equipe.',ephemeral:true});if(i.isButton()&&i.customId==='ticket_claim'){const k=String(i.channel.topic||'').split(':')[2];if(!staff(i,db.ticketConfig.teams[k]))return i.reply({content:'❌ Você não pode assumir este ticket.',ephemeral:true});return i.reply({content:`🔒 Ticket assumido por ${i.user}.`})}if(i.isButton()&&i.customId==='ticket_close')return close(i);if(i.isButton()&&i.customId==='ticket_notify')return i.reply({content:`🔔 ${i.user}, a equipe foi notificada.`});if(i.isStringSelectMenu()&&i.customId==='ticket_options')return i.reply({content:i.values[0]==='staff'?'🛠️ Ferramentas exclusivas para a equipe.':'👤 Opções disponíveis para você.',ephemeral:true});if(i.isChatInputCommand()&&i.commandName==='ticket'&&i.memberPermissions?.has(PermissionFlagsBits.ManageGuild))return i.reply(panel())}catch(e){console.error('[TicketControlSuite]',e);if(!i.replied&&!i.deferred)i.reply({content:'❌ Não foi possível concluir essa ação.',ephemeral:true}).catch(()=>{})}})}
module.exports={install,panel};
