const { Events, ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionFlagsBits, ChannelType, StringSelectMenuBuilder, StringSelectMenuOptionBuilder } = require('discord.js');
const { db, save } = require('./ProfessionalSuite');
const BANNER = 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663954246112/thbmdKXerDBxYWXy.png';
const TEAMS = { suporte: ['Suporte', 'Problemas e dúvidas', '🛠️'], financeiro: ['Financeiro', 'Pagamentos e comprovantes', '💳'], vendas: ['Vendas', 'Produtos e pedidos', '🛒'], parceria: ['Parceria', 'Propostas e parcerias', '🤝'] };
function ensure() { db.ticketPanel ||= {}; return db.ticketPanel; }
function cfg(id) { const all = ensure(); all[id] ||= { storeName: 'Shadow Games', title: 'Central de Atendimento', description: 'Escolha abaixo o tipo de atendimento que precisa.', color: '#f1c40f', banner: BANNER, categoryId: '', panelChannelId: '', teams: TEAMS, categoryByTeam: {}, roleByTeam: {}, welcome: 'Olá {user}! Explique detalhadamente como podemos ajudar.' }; const c = all[id]; c.teams ||= TEAMS; c.categoryByTeam ||= {}; c.roleByTeam ||= {}; return c; }
function menu(c) { return [new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('tp_open').setPlaceholder('Clique aqui para ver as opções').addOptions(Object.entries(c.teams).slice(0, 25).map(([k, v]) => new StringSelectMenuOptionBuilder().setValue(k).setLabel(v[0]).setDescription(v[1]).setEmoji(v[2]))))]; }
async function sendPanel(guild, channel, options = {}) { const c = cfg(guild.id); Object.assign(c, options, { panelChannelId: channel.id }); save(); const e = new EmbedBuilder().setColor(c.color).setTitle(c.title || c.storeName).setDescription(c.description); if (c.banner) e.setImage(c.banner); return channel.send({ embeds: [e], components: menu(c) }); }
function purchases(uid) { const out = []; const seen = new Set(); function scan(x) { if (!x || typeof x !== 'object' || seen.has(x)) return; seen.add(x); if (Array.isArray(x)) return x.forEach(scan); const id = String(x.userId || x.discordId || x.discordID || x.customerId || x.ownerId || ''); const n = x.product || x.productName || x.nome || x.name || x.item || x.campo; if (id === String(uid) && n) out.push({ n: String(n), p: String(x.price || x.valor || x.value || ''), d: String(x.date || x.data || x.createdAt || '') }); Object.values(x).forEach(scan); } scan(db); return out.slice(0, 25); }
function buyPanel(uid) { const list = purchases(uid); const e = new EmbedBuilder().setColor('#f1c40f').setTitle('🛒 Compras encontradas').setDescription(list.length ? `Encontramos ${list.length} compra(s) para você.\n\nCaso não seja sobre um produto adquirido, escolha a opção abaixo.` : 'Não encontramos compras vinculadas a este usuário.'); const opts = list.map((p, i) => new StringSelectMenuOptionBuilder().setValue(`buy:${i}`).setLabel(p.n.slice(0, 100)).setDescription([p.p, p.d].filter(Boolean).join(' • ').slice(0, 100) || 'Compra registrada')); opts.push(new StringSelectMenuOptionBuilder().setValue('buy:none').setLabel('Não é sobre um produto adquirido').setDescription('Continuar sem selecionar uma compra').setEmoji('❌')); return { embeds: [e], components: [new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('tp_buy').setPlaceholder('Selecione uma de suas compras').addOptions(opts))] }; }
function buttons() { return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('tp_notify').setLabel('Notificar equipe').setEmoji('🔔').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('tp_claim').setLabel('Assumir').setEmoji('📁').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('tp_transcript').setLabel('Salvar transcript').setEmoji('📄').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('tp_close').setLabel('Excluir').setEmoji('🗑️').setStyle(ButtonStyle.Danger))]; }
async function open(i, team) { const c = cfg(i.guild.id), d = c.teams[team] || TEAMS.suporte, catId = c.categoryByTeam[team] || c.categoryId, cat = catId && i.guild.channels.cache.get(catId), rid = c.roleByTeam[team], name = `${team}-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 90), ow = [{ id: i.guild.roles.everyone.id, deny: ['ViewChannel'] }, { id: i.user.id, allow: ['ViewChannel', 'SendMessages', 'ReadMessageHistory', 'AttachFiles'] }, { id: i.client.user.id, allow: ['ViewChannel', 'SendMessages', 'ReadMessageHistory', 'ManageChannels'] }]; if (rid) ow.push({ id: rid, allow: ['ViewChannel', 'SendMessages', 'ReadMessageHistory'] }); const ch = await i.guild.channels.create({ name, type: ChannelType.GuildText, parent: cat?.type === ChannelType.GuildCategory ? cat.id : undefined, topic: `ticket:${i.user.id}:${team}:aberto`, permissionOverwrites: ow }); const e = new EmbedBuilder().setColor(c.color).setTitle(`${d[2]} ${d[0]}`).setDescription((c.welcome || 'Olá {user}! Explique detalhadamente como podemos ajudar.').replace('{user}', i.user.toString())).addFields({ name: 'Categoria', value: d[1] }); if (c.banner) e.setThumbnail(c.banner); await ch.send({ content: rid ? `${i.user} <@&${rid}>` : i.user.toString(), embeds: [e], components: buttons() }); await ch.send(buyPanel(i.user.id)); return i.reply({ content: `✅ Ticket criado: ${ch}`, ephemeral: true }); }
async function install(client) { client.on(Events.InteractionCreate, async i => { try { if (!i.guild) return; if (i.isStringSelectMenu?.() && i.customId === 'tp_open') return open(i, i.values[0]); if (i.isStringSelectMenu?.() && i.customId === 'tp_buy') return i.reply({ content: i.values[0] === 'buy:none' ? '✅ Atendimento sem produto selecionado.' : `✅ Compra selecionada: ${i.values[0]}`, ephemeral: true }); if (!i.isButton?.()) return; if (i.customId === 'tp_notify') { const c = cfg(i.guild.id), t = (i.channel.topic || '').split(':')[2], r = c.roleByTeam[t]; return i.reply({ content: `🔔 Equipe notificada por ${i.user}.${r ? ` <@&${r}>` : ''}` }); } if (i.customId === 'tp_claim') return i.reply({ content: `✅ ${i.user} assumiu este ticket.` }); if (i.customId === 'tp_transcript') { if (!i.memberPermissions?.has(PermissionFlagsBits.ManageChannels)) return i.reply({ content: '❌ Apenas a equipe pode salvar o transcript.', ephemeral: true }); const m = await i.channel.messages.fetch({ limit: 100 }); const text = [...m.values()].reverse().map(x => `[${x.createdAt.toISOString()}] ${x.author.tag}: ${x.content}`).join('\n'); return i.reply({ content: '📄 Transcript salvo:', files: [{ attachment: Buffer.from(text), name: `transcript-${i.channel.name}.txt` }] }); } if (i.customId === 'tp_close') { if (!i.memberPermissions?.has(PermissionFlagsBits.ManageChannels)) return i.reply({ content: '❌ Você precisa de Gerenciar Canais.', ephemeral: true }); await i.reply({ content: '🔒 Ticket fechado. Este canal será excluído em 5 segundos.' }); setTimeout(() => i.channel.delete().catch(() => {}), 5000); } } catch (e) { console.error('[TicketPanel]', e); if (!i.replied && !i.deferred) i.reply({ content: '❌ Não foi possível concluir esta ação.', ephemeral: true }).catch(() => {}); } }); }
module.exports = { install, sendPanel, cfg, TEAMS };
