const {Events,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits,ChannelType,AttachmentBuilder}=require('discord.js');
const {db,save}=require('./ProfessionalSuite');
const teams={suporte:{name:'Suporte ao Cliente',description:'Ticket exclusivo para suporte de produtos.',emoji:'🛠️'},duvidas:{name:'Dúvidas',description:'Tire suas dúvidas e saiba mais sobre nós.',emoji:'❓'},parceria:{name:'Parceria',description:'Envie sua proposta de parceria para nossa equipe.',emoji:'🤝'},comprar:{name:'Pagar/Comprar',description:'Realize o pagamento de algum produto.',emoji:'🛒'}};
function ensure(){db.ticketConfig||={};Object.assign(db.ticketConfig,{panelTitle:'Central de Atendimento | Shadow Games',panelDescription:'Nosso atendimento é privado e funciona 24 horas, sujeito à disponibilidade da equipe.',panelColor:'#5865f2',panelImage:'',logsChannelId:'',...db.ticketConfig});db.ticketConfig.teams={...teams,...(db.ticketConfig.teams||{})};db.ticketConfig.permissions||={};save()}
const slug=s=>String(s||'usuario').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').slice(0,22).replace(/^-|-$/g,'')||'usuario';
const staff=(i,t)=>i.memberPermissions?.has(PermissionFlagsBits.Administrator)||Boolean(i.member?.roles?.cache&&[t?.roleId,db.ticketConfig.permissions.claimRole,db.ticketConfig.permissions.closeRole].filter(Boolean).some(x=>i.member.roles.cache.has(x)));
function categories(){return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_category').setPlaceholder('Clique aqui para ver as opções').addOptions(Object.entries(db.ticketConfig.teams).slice(0,25).map(([value,t])=>({label:t.name,description:t.description?.slice(0,100),value,emoji:t.emoji||'🎫'}))))}
function controls(){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_notify').setLabel('Notificar').setEmoji('🔔').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('ticket_claim').setLabel('Assumir Ticket').setEmoji('🙋‍♂️').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket_close').setLabel('Deletar e Salvar').setEmoji('⛔').setStyle(ButtonStyle.Danger)),new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('ticket_options').setPlaceholder('Selecione um painel de opções').addOptions({label:'Painel Staff',value:'staff',emoji:'🛡️'},{label:'Dúvidas para Staff',value:'staff_questions',emoji:'❔'},{label:'Fechamento',value:'close',emoji:'🔒'},{label:'Cupom disponível para você',value:'coupon',emoji:'🎟️'}))]}
function panelMessage(){const c=db.ticketConfig,e=new EmbedBuilder().setColor(c.panelColor).setTitle(c.panelTitle).setDescription(c.panelDescription);if(c.panelImage)e.setImage(c.panelImage);return{embeds:[e],components:[categories()]}}
async function open(i,key){const t=db.ticketConfig.teams[key]||teams.suporte,g=i.guild,old=g.channels.cache.find(c=>c.topic===`ticket:${i.user.id}:${key}`);if(old)return i.reply({content:`Você já possui um ticket aberto: ${old}`,ephemeral:true});const p=[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.AttachFiles]},{id:g.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ManageChannels,PermissionFlagsBits.ReadMessageHistory]}];if(t.roleId)p.push({id:t.roleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const c=await g.channels.create({name:`${slug(t.name)}-${slug(i.user.username)}-${String(i.user.id).slice(-4)}`,type:ChannelType.GuildText,parent:t.categoryId||undefined,topic:`ticket:${i.user.id}:${key}`,permissionOverwrites:p});const e=new EmbedBuilder().setColor(db.ticketConfig.panelColor).setTitle(`🎫 ${t.name}`).setDescription(`Olá ${i.user}, sua solicitação foi criada.\n\n**Categoria:** ${t.name}\n**ID do usuário:** ${i.user.id}\n\nA equipe responderá assim que possível.`).setFooter({text:'Shadow Games • Atendimento privado'});await c.send({content:`${i.user}`,embeds:[e],components:controls()});return i.reply({content:`✅ Seu ticket foi criado: ${c}`,ephemeral:true})}
async function close(i){const key=String(i.channel.topic||'').split(':')[2];if(!staff(i,db.ticketConfig.teams[key]))return i.reply({content:'❌ Somente a equipe pode fechar este ticket.',ephemeral:true});await i.deferReply({ephemeral:true});const ms=await i.channel.messages.fetch({limit:100}),txt=[...ms.values()].sort((a,b)=>a.createdTimestamp-b.createdTimestamp).map(m=>`[${new Date(m.createdTimestamp).toISOString()}] ${m.author.tag}: ${m.content||'[embed/anexo]'}`).join('\n');const log=db.ticketConfig.logsChannelId?await i.guild.channels.fetch(db.ticketConfig.logsChannelId).catch(()=>null):null;if(log?.isTextBased())await log.send({content:`📁 Ticket fechado: **${i.channel.name}**\nAberto por: <@${String(i.channel.topic).split(':')[1]}>\nFechado por: ${i.user}`,files:[new AttachmentBuilder(Buffer.from(txt||'Sem mensagens.'),{name:`${i.channel.name}.txt`})]});await i.editReply({content:log?'✅ Transcrição salva nos logs.':'✅ Ticket encerrado.'});setTimeout(()=>i.channel.delete('Ticket encerrado'),1500)}
async function install(client){ensure();client.on(Events.InteractionCreate,async i=>{try{if(i.isStringSelectMenu()&&i.customId==='ticket_category')return open(i,i.values[0]);if(i.isButton()&&i.customId==='ticket_claim'){const k=String(i.channel.topic||'').split(':')[2];if(!staff(i,db.ticketConfig.teams[k]))return i.reply({content:'❌ Você não pode assumir este ticket.',ephemeral:true});await i.channel.setTopic(`${i.channel.topic}:assumido:${i.user.id}`);return i.reply({content:`🙋‍♂️ Ticket assumido por ${i.user}.`})}if(i.isButton()&&i.customId==='ticket_close')return close(i);if(i.isButton()&&i.customId==='ticket_notify')return i.reply({content:`🔔 ${i.user}, a equipe foi notificada neste ticket.`});if(i.isStringSelectMenu()&&i.customId==='ticket_options')return i.reply({content:i.values[0]==='coupon'?'🎟️ Consulte a equipe sobre cupons.':i.values[0]==='close'?'Use Deletar e Salvar para encerrar.':i.values[0]==='staff'?'🛡️ Ferramentas Staff disponíveis no painel.':'❔ Escreva sua dúvida para a equipe.',ephemeral:true});if(i.isChatInputCommand()&&i.commandName==='ticketpainel'){if(!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild))return i.reply({content:'Apenas administradores podem publicar o painel.',ephemeral:true});return i.reply(panelMessage())}}catch(e){console.error('[TicketControlSuite]',e);if(!i.replied&&!i.deferred)i.reply({content:'❌ Não foi possível concluir essa ação.',ephemeral:true}).catch(()=>{})}})}
module.exports={install,panelMessage,ensure};
