'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const suite = fs.readFileSync(path.join(root, 'LogSuite.js'), 'utf8');
const panel = fs.readFileSync(path.join(root, 'Eventos/Sistema De Configuracao/configRoles&Channels.js'), 'utf8');
const professional = fs.readFileSync(path.join(root, 'ProfessionalSuite.js'), 'utf8');
const loader = fs.readFileSync(path.join(root, 'Handler/events.js'), 'utf8');
const command = fs.readFileSync(path.join(root, 'ComandosSlash/Administracao/logs.js'), 'utf8');
assert.match(suite, /serverLogs\[guildId\]/);
assert.match(suite, /function syncPanelChannel/);
assert.match(suite, /logmensagem: \['mensagem_apagada', 'mensagem_editada'\]/);
assert.match(panel, /syncPanelChannel\(interaction.guild.id, 'logentrada'/);
assert.match(panel, /syncPanelChannel\(interaction.guild.id, 'trafegocall'/);
assert.doesNotMatch(professional, /client\.on\(Events\.MessageDelete/);
assert.doesNotMatch(professional, /client\.on\(Events\.MessageUpdate/);
assert.match(loader, /interactionHandlers/);
assert.match(command, /setChannel\(interaction.guild.id/);
console.log('log routing: ok');
